on:
  push:
    tags:
      - 'v*.*.*' # Trigger only on tags like v1.2.3
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - '.gitattributes'
      - 'COPYRIGHT'
  workflow_dispatch:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
    - name: Compile
      run: |
        cmake -S . -B build -G Ninja
        cmake --build build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-linux-${{ env.VERSION }}
        path: |
          build/Release/**/*
  windows-mingw:
    name: Windows MinGW
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        cmake -S . -B build -G Ninja
        cmake --build build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-windows-mingw-${{ env.VERSION }}
        path: |
          build/Release/**/*.dll
          build/Release/**/*.exe
          build/Release/**/*.qvm
  macos:
    name: macOS
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        cmake -S . -B build -G Ninja
        cmake --build build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-macOS-${{ env.VERSION }}
        path: |
          build/Release/**/*