name: Build
on:
  schedule:
    - cron: "0 0 * * 0"  # runs weekly on Sunday at midnight UTC

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
    - name: Compile
      run: |
        cmake -S . -B build -G Ninja
        cmake --build build
        echo "VERSION=$(cat build/version.txt)" >> $GITHUB_ENV
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-linux-${{ env.VERSION }}
        path: |
          build/Release/**/*
  windows-mingw:
    name: Windows MinGW
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        cmake -S . -B build -G Ninja
        cmake --build build
        $version = Get-Content build/version.txt -Raw
        Add-Content -Path $env:GITHUB_ENV -Value "VERSION=$version"
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-windows-mingw-${{ env.VERSION }}
        path: |
          build/Release/**/*.dll
          build/Release/**/*.exe
          build/Release/**/*.qvm
  macos:
    name: macOS
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        cmake -S . -B build -G Ninja
        cmake --build build
        echo "VERSION=$(cat build/version.txt)" >> $GITHUB_ENV
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-macOS-${{ env.VERSION }}
        path: |
          build/Release/**/*