name: Build
on:
  workflow_dispatch:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
      - name: Compile
        run: |
          cmake -S . -B build -G Ninja
          cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build
          if-no-files-found: error
          retention-days: 5

  windows-mingw:
    name: Windows MinGW
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          cmake -S . -B build -G Ninja
          cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: windows-mingw-build
          path: build
          if-no-files-found: error
          retention-days: 5

  macos:
    name: macOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          cmake -S . -B build -G Ninja
          cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build
          if-no-files-found: error
          retention-days: 5

  create-release:
    needs: [linux, windows-mingw, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: Zip Linux Build
        run: |
          cd linux-build
          zip -r quake3e-linux-x86_64.zip lburg q3asm q3cpp q3lcc q3rcc stringify
      - name: Zip Windows Build
        run: |
          cd windows-mingw-build
          zip -r quake3e-windows-mingw-x86_64.zip lburg.exe q3asm.exe q3cpp.exe q3lcc.exe q3rcc.exe stringify.exe
      - name: Zip macOS Build
        run: |
          cd macos-build
          zip -r quake3e-macos-x86_64.zip lburg q3asm q3cpp q3lcc q3rcc stringify
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: latest
          release_name: Latest Release
          draft: false
          prerelease: false
      - name: Upload Release Assets
        run: |
          gh release upload latest quake3e-linux-x86_64.zip quake3e-windows-mingw-x86_64.zip quake3e-macos-x86_64.zip