name: Build
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Linux
        run: |
          cmake -S . -B build-linux -G Ninja
          cmake --build build-linux
          zip -j qvm-tools-linux-${{ runner.arch }}.zip build-linux/lburg build-linux/q3asm build-linux/q3cpp build-linux/q3lcc build-linux/q3rcc build-linux/stringify

      - name: Build Windows MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja
        run: |
          cmake -S . -B build-windows -G Ninja
          cmake --build build-windows
          Compress-Archive -Path build-windows/lburg.exe, build-windows/q3asm.exe, build-windows/q3cpp.exe, build-windows/q3lcc.exe, build-windows/q3rcc.exe, build-windows/stringify.exe -DestinationPath qvm-tools-windows-${{ runner.arch }}.zip

      - name: Build macOS
        run: |
          cmake -S . -B build-macos -G Ninja
          cmake --build build-macos
          zip -j qvm-tools-macos-${{ runner.arch }}.zip build-macos/lburg build-macos/q3asm build-macos/q3cpp build-macos/q3lcc build-macos/q3rcc build-macos/stringify
        shell: bash # for consistency

      - name: Delete existing latest release
        uses: dev-drprasad/delete-tag-and-release@v1
        with:
          tag_name: latest
          repo: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: latest
          release_name: Latest Release
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./qvm-tools-linux-${{ runner.arch }}.zip
          asset_name: qvm-tools-linux-${{ runner.arch }}.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./qvm-tools-windows-${{ runner.arch }}.zip
          asset_name: qvm-tools-windows-${{ runner.arch }}.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./qvm-tools-macos-${{ runner.arch }}.zip
          asset_name: qvm-tools-macos-${{ runner.arch }}.zip
          asset_content_type: application/zip